// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmnieeynahbakhgisxof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbmllZXluYWhiYWtoZ2lzeG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODIxNTUsImV4cCI6MjA2Mzk1ODE1NX0.q50knjWvqnz_2eJ46_NkOTkatZzvS3nLRfGMpv_moOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);